name: test continue-on-error
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'continue-on-error value for the job'
        required: true
      step:
        description: 'continue-on-error value for the step'
        required: true
  
jobs:
  test-job:
    name: test job
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event.inputs.job }}
    steps:
      - name: step 1 (OK)
        run: echo "OK"

      - name: step 2 (NG)
        continue-on-error: ${{ github.event.inputs.step }}
        run: echo "NG"; exit 1

      - name: step 3 (OK)
        run: echo "OK"

  post-job:
    name: post job
    runs-on: ubuntu-latest
    steps:
      - name: post step
        run: echo "post job"